var hierarchy =
[
    [ "igl::AABB&lt; DerivedV, DIM &gt;", "classigl_1_1AABB.html", null ],
    [ "igl::active_set_params", "structigl_1_1active__set__params.html", null ],
    [ "igl::ARAPData", "structigl_1_1ARAPData.html", null ],
    [ "igl::ArapDOFData&lt; LbsMatrixType, SSCALAR &gt;", "structigl_1_1ArapDOFData.html", null ],
    [ "igl::AtA_cached_data", "structigl_1_1AtA__cached__data.html", null ],
    [ "igl::BBWData", "classigl_1_1BBWData.html", null ],
    [ "igl::copyleft::cgal::BinaryWindingNumberOperations&lt; Op &gt;", "classigl_1_1copyleft_1_1cgal_1_1BinaryWindingNumberOperations.html", null ],
    [ "igl::copyleft::cgal::BinaryWindingNumberOperations&lt; MESH_BOOLEAN_TYPE_INTERSECT &gt;", "classigl_1_1copyleft_1_1cgal_1_1BinaryWindingNumberOperations_3_01MESH__BOOLEAN__TYPE__INTERSECT_01_4.html", null ],
    [ "igl::copyleft::cgal::BinaryWindingNumberOperations&lt; MESH_BOOLEAN_TYPE_MINUS &gt;", "classigl_1_1copyleft_1_1cgal_1_1BinaryWindingNumberOperations_3_01MESH__BOOLEAN__TYPE__MINUS_01_4.html", null ],
    [ "igl::copyleft::cgal::BinaryWindingNumberOperations&lt; MESH_BOOLEAN_TYPE_RESOLVE &gt;", "classigl_1_1copyleft_1_1cgal_1_1BinaryWindingNumberOperations_3_01MESH__BOOLEAN__TYPE__RESOLVE_01_4.html", null ],
    [ "igl::copyleft::cgal::BinaryWindingNumberOperations&lt; MESH_BOOLEAN_TYPE_UNION &gt;", "classigl_1_1copyleft_1_1cgal_1_1BinaryWindingNumberOperations_3_01MESH__BOOLEAN__TYPE__UNION_01_4.html", null ],
    [ "igl::copyleft::cgal::BinaryWindingNumberOperations&lt; MESH_BOOLEAN_TYPE_XOR &gt;", "classigl_1_1copyleft_1_1cgal_1_1BinaryWindingNumberOperations_3_01MESH__BOOLEAN__TYPE__XOR_01_4.html", null ],
    [ "igl::copyleft::tetgen::CDTParam", "structigl_1_1copyleft_1_1tetgen_1_1CDTParam.html", null ],
    [ "igl::copyleft::cgal::CSGTree", "classigl_1_1copyleft_1_1cgal_1_1CSGTree.html", null ],
    [ "igl::embree::EmbreeDevice", "structigl_1_1embree_1_1EmbreeDevice.html", null ],
    [ "igl::embree::EmbreeIntersector", "classigl_1_1embree_1_1EmbreeIntersector.html", null ],
    [ "igl::get_options&lt; Derived, typename &gt;", "structigl_1_1get__options.html", null ],
    [ "igl::get_options&lt; Derived, std::void_t&lt; decltype(Derived::Options)&gt; &gt;", "structigl_1_1get__options_3_01Derived_00_01std_1_1void__t_3_01decltype_07Derived_1_1Options_08_4_01_4.html", null ],
    [ "igl::opengl::gliGenericImage", "structigl_1_1opengl_1_1gliGenericImage.html", null ],
    [ "igl::HalfEdgeIterator&lt; DerivedF, DerivedFF, DerivedFFi &gt;", "classigl_1_1HalfEdgeIterator.html", null ],
    [ "igl::HeatGeodesicsData&lt; Scalar &gt;", "structigl_1_1HeatGeodesicsData.html", null ],
    [ "igl::embree::EmbreeRenderer::Hit", "structigl_1_1embree_1_1EmbreeRenderer_1_1Hit.html", null ],
    [ "igl::Hit&lt; Scalar &gt;", "structigl_1_1Hit.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; T &gt;", "classImGui_1_1ImGuiDataTypeTraits.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; double &gt;", "classImGui_1_1ImGuiDataTypeTraits_3_01double_01_4.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; float &gt;", "classImGui_1_1ImGuiDataTypeTraits_3_01float_01_4.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; int &gt;", "classImGui_1_1ImGuiDataTypeTraits_3_01int_01_4.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; long long &gt;", "classImGui_1_1ImGuiDataTypeTraits_3_01long_01long_01_4.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; unsigned int &gt;", "classImGui_1_1ImGuiDataTypeTraits_3_01unsigned_01int_01_4.html", null ],
    [ "ImGui::ImGuiDataTypeTraits&lt; unsigned long long &gt;", "classImGui_1_1ImGuiDataTypeTraits_3_01unsigned_01long_01long_01_4.html", null ],
    [ "igl::opengl::glfw::imgui::ImGuiWidget", "classigl_1_1opengl_1_1glfw_1_1imgui_1_1ImGuiWidget.html", [
      [ "igl::opengl::glfw::imgui::ImGuiMenu", "classigl_1_1opengl_1_1glfw_1_1imgui_1_1ImGuiMenu.html", null ],
      [ "igl::opengl::glfw::imgui::ImGuizmoWidget", "classigl_1_1opengl_1_1glfw_1_1imgui_1_1ImGuizmoWidget.html", null ],
      [ "igl::opengl::glfw::imgui::SelectionWidget", "classigl_1_1opengl_1_1glfw_1_1imgui_1_1SelectionWidget.html", null ]
    ] ],
    [ "igl::IndexDimLessThan&lt; T &gt;", "structigl_1_1IndexDimLessThan.html", null ],
    [ "igl::IndexedPointerBase", "structigl_1_1IndexedPointerBase.html", [
      [ "igl::IndexedPointer< T >", "structigl_1_1IndexedPointer.html", null ]
    ] ],
    [ "igl::IndexEquals&lt; T &gt;", "structigl_1_1IndexEquals.html", null ],
    [ "igl::IndexLessThan&lt; T &gt;", "structigl_1_1IndexLessThan.html", null ],
    [ "igl::IndexRowEquals&lt; T &gt;", "structigl_1_1IndexRowEquals.html", null ],
    [ "igl::IndexRowLessThan&lt; T &gt;", "structigl_1_1IndexRowLessThan.html", null ],
    [ "igl::IndexVectorLessThan&lt; T &gt;", "structigl_1_1IndexVectorLessThan.html", null ],
    [ "igl::serialization::is_eigen_type&lt; T &gt;", "structigl_1_1serialization_1_1is__eigen__type.html", null ],
    [ "igl::xml::serialization_xml::is_eigen_type&lt; T &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__eigen__type.html", null ],
    [ "igl::serialization::is_eigen_type&lt; Eigen::Array&lt; T, R, C, P, MR, MC &gt; &gt;", "structigl_1_1serialization_1_1is__eigen__type_3_01Eigen_1_1Array_3_01T_00_01R_00_01C_00_01P_00_01MR_00_01MC_01_4_01_4.html", null ],
    [ "igl::serialization::is_eigen_type&lt; Eigen::Matrix&lt; T, R, C, P, MR, MC &gt; &gt;", "structigl_1_1serialization_1_1is__eigen__type_3_01Eigen_1_1Matrix_3_01T_00_01R_00_01C_00_01P_00_01MR_00_01MC_01_4_01_4.html", null ],
    [ "igl::xml::serialization_xml::is_eigen_type&lt; Eigen::Matrix&lt; T, R, C, P, MR, MC &gt; &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__eigen__type_3_01Eigen_1_1Matrix_3_01T_00_01R_00_01514ce92cafd2800841c034018462fddd.html", null ],
    [ "igl::serialization::is_eigen_type&lt; Eigen::SparseMatrix&lt; T, P, I &gt; &gt;", "structigl_1_1serialization_1_1is__eigen__type_3_01Eigen_1_1SparseMatrix_3_01T_00_01P_00_01I_01_4_01_4.html", null ],
    [ "igl::xml::serialization_xml::is_eigen_type&lt; Eigen::SparseMatrix&lt; T, P, I &gt; &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__eigen__type_3_01Eigen_1_1SparseMatrix_3_01T_00_01P_00_01I_01_4_01_4.html", null ],
    [ "igl::serialization::is_serializable&lt; T &gt;", "structigl_1_1serialization_1_1is__serializable.html", null ],
    [ "igl::xml::serialization_xml::is_serializable&lt; T &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__serializable.html", null ],
    [ "igl::serialization::is_smart_ptr&lt; T &gt;", "structigl_1_1serialization_1_1is__smart__ptr.html", null ],
    [ "igl::serialization::is_smart_ptr&lt; std::shared_ptr&lt; T &gt; &gt;", "structigl_1_1serialization_1_1is__smart__ptr_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "igl::serialization::is_smart_ptr&lt; std::unique_ptr&lt; T &gt; &gt;", "structigl_1_1serialization_1_1is__smart__ptr_3_01std_1_1unique__ptr_3_01T_01_4_01_4.html", null ],
    [ "igl::serialization::is_smart_ptr&lt; std::weak_ptr&lt; T &gt; &gt;", "structigl_1_1serialization_1_1is__smart__ptr_3_01std_1_1weak__ptr_3_01T_01_4_01_4.html", null ],
    [ "igl::serialization::is_stl_container&lt; T &gt;", "structigl_1_1serialization_1_1is__stl__container.html", null ],
    [ "igl::xml::serialization_xml::is_stl_container&lt; T &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__stl__container.html", null ],
    [ "igl::serialization::is_stl_container&lt; std::list&lt; T &gt; &gt;", "structigl_1_1serialization_1_1is__stl__container_3_01std_1_1list_3_01T_01_4_01_4.html", null ],
    [ "igl::serialization::is_stl_container&lt; std::map&lt; T1, T2 &gt; &gt;", "structigl_1_1serialization_1_1is__stl__container_3_01std_1_1map_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "igl::xml::serialization_xml::is_stl_container&lt; std::map&lt; T1, T2 &gt; &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__stl__container_3_01std_1_1map_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "igl::serialization::is_stl_container&lt; std::pair&lt; T1, T2 &gt; &gt;", "structigl_1_1serialization_1_1is__stl__container_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "igl::xml::serialization_xml::is_stl_container&lt; std::pair&lt; T1, T2 &gt; &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__stl__container_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "igl::serialization::is_stl_container&lt; std::set&lt; T &gt; &gt;", "structigl_1_1serialization_1_1is__stl__container_3_01std_1_1set_3_01T_01_4_01_4.html", null ],
    [ "igl::xml::serialization_xml::is_stl_container&lt; std::set&lt; T &gt; &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__stl__container_3_01std_1_1set_3_01T_01_4_01_4.html", null ],
    [ "igl::serialization::is_stl_container&lt; std::vector&lt; T1, T2 &gt; &gt;", "structigl_1_1serialization_1_1is__stl__container_3_01std_1_1vector_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "igl::xml::serialization_xml::is_stl_container&lt; std::vector&lt; T1, T2 &gt; &gt;", "structigl_1_1xml_1_1serialization__xml_1_1is__stl__container_3_01std_1_1vector_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "std::istream", null, [
      [ "igl::FileMemoryStream", "structigl_1_1FileMemoryStream.html", null ]
    ] ],
    [ "igl::KelvinletParams&lt; Scalar &gt;", "structigl_1_1KelvinletParams.html", null ],
    [ "igl::matlab::MatlabWorkspace", "classigl_1_1matlab_1_1MatlabWorkspace.html", null ],
    [ "igl::opengl::MeshGL", "classigl_1_1opengl_1_1MeshGL.html", null ],
    [ "igl::min_quad_with_fixed_data&lt; T &gt;", "structigl_1_1min__quad__with__fixed__data.html", null ],
    [ "igl::mosek::MosekData", "structigl_1_1mosek_1_1MosekData.html", null ],
    [ "igl::MshLoader::msh_struct", "structigl_1_1MshLoader_1_1msh__struct.html", null ],
    [ "igl::MshLoader", "classigl_1_1MshLoader.html", null ],
    [ "igl::MshSaver", "classigl_1_1MshSaver.html", null ],
    [ "igl::PlainMatrixHelper&lt; Derived, Rows, Cols, Options &gt;", "structigl_1_1PlainMatrixHelper.html", null ],
    [ "igl::PlainVectorHelper&lt; Derived, Size, Options &gt;", "structigl_1_1PlainVectorHelper.html", null ],
    [ "igl::copyleft::cgal::RemeshSelfIntersectionsParam", "structigl_1_1copyleft_1_1cgal_1_1RemeshSelfIntersectionsParam.html", null ],
    [ "igl::triangle::SCAFData", "structigl_1_1triangle_1_1SCAFData.html", null ],
    [ "igl::copyleft::cgal::SelfIntersectMesh&lt; Kernel, DerivedV, DerivedF, DerivedVV, DerivedFF, DerivedIF, DerivedJ, DerivedIM &gt;", "classigl_1_1copyleft_1_1cgal_1_1SelfIntersectMesh.html", null ],
    [ "igl::SerializableBase", "structigl_1_1SerializableBase.html", [
      [ "igl::Serializable", "classigl_1_1Serializable.html", null ],
      [ "igl::xml::XMLSerializableBase", "structigl_1_1xml_1_1XMLSerializableBase.html", [
        [ "igl::xml::XMLSerializable", "classigl_1_1xml_1_1XMLSerializable.html", null ]
      ] ]
    ] ],
    [ "igl::ShapeupData", "structigl_1_1ShapeupData.html", null ],
    [ "igl::SLIMData", "structigl_1_1SLIMData.html", null ],
    [ "igl::SortableRow&lt; T &gt;", "classigl_1_1SortableRow.html", null ],
    [ "igl::SphereMeshWedge&lt; Scalar &gt;", "classigl_1_1SphereMeshWedge.html", null ],
    [ "std::streambuf", null, [
      [ "igl::FileMemoryBuffer", "structigl_1_1FileMemoryBuffer.html", [
        [ "igl::FileMemoryStream", "structigl_1_1FileMemoryStream.html", null ]
      ] ]
    ] ],
    [ "igl::opengl::MeshGL::TextGL", "structigl_1_1opengl_1_1MeshGL_1_1TextGL.html", null ],
    [ "igl::opengl::TgaFooter", "structigl_1_1opengl_1_1TgaFooter.html", null ],
    [ "igl::opengl::TgaHeader", "structigl_1_1opengl_1_1TgaHeader.html", null ],
    [ "igl::Timer", "classigl_1_1Timer.html", null ],
    [ "igl::opengl::glfw::Viewer", "classigl_1_1opengl_1_1glfw_1_1Viewer.html", null ],
    [ "igl::opengl::ViewerCore", "classigl_1_1opengl_1_1ViewerCore.html", null ],
    [ "igl::opengl::ViewerData", "classigl_1_1opengl_1_1ViewerData.html", null ],
    [ "igl::opengl::glfw::ViewerPlugin", "classigl_1_1opengl_1_1glfw_1_1ViewerPlugin.html", [
      [ "igl::opengl::glfw::imgui::ImGuiPlugin", "classigl_1_1opengl_1_1glfw_1_1imgui_1_1ImGuiPlugin.html", null ]
    ] ],
    [ "igl::WindingNumberAntipodalScene&lt; Scalar &gt;", "classigl_1_1WindingNumberAntipodalScene.html", null ],
    [ "igl::copyleft::cgal::WindingNumberFilter&lt; T &gt;", "classigl_1_1copyleft_1_1cgal_1_1WindingNumberFilter.html", null ],
    [ "igl::copyleft::cgal::WindingNumberFilter&lt; KEEP_ALL &gt;", "classigl_1_1copyleft_1_1cgal_1_1WindingNumberFilter_3_01KEEP__ALL_01_4.html", null ],
    [ "igl::copyleft::cgal::WindingNumberFilter&lt; KEEP_INSIDE &gt;", "classigl_1_1copyleft_1_1cgal_1_1WindingNumberFilter_3_01KEEP__INSIDE_01_4.html", null ],
    [ "igl::WindingNumberTree&lt; Scalar, Index &gt;", "classigl_1_1WindingNumberTree.html", [
      [ "igl::WindingNumberAABB< Scalar, Index >", "classigl_1_1WindingNumberAABB.html", null ]
    ] ]
];