var searchData=
[
  ['halfedgeiterator_0',['HalfEdgeIterator',['../classigl_1_1HalfEdgeIterator.html#ade6f831eefbe8752706db4e8c5ffebb9',1,'igl::HalfEdgeIterator']]],
  ['harmonic_1',['harmonic',['../namespaceigl.html#a5ade90c5c56252e2c88f4452996c50a0',1,'igl::harmonic(const Eigen::MatrixBase&lt; DerivedV &gt; &amp;V, const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, const Eigen::MatrixBase&lt; Derivedb &gt; &amp;b, const Eigen::MatrixBase&lt; Derivedbc &gt; &amp;bc, const int k, Eigen::PlainObjectBase&lt; DerivedW &gt; &amp;W)'],['../namespaceigl.html#ac3baf24e87966423e7c6dac58f40c406',1,'igl::harmonic(const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, const Eigen::MatrixBase&lt; Derivedb &gt; &amp;b, const Eigen::MatrixBase&lt; Derivedbc &gt; &amp;bc, const int k, Eigen::PlainObjectBase&lt; DerivedW &gt; &amp;W)'],['../namespaceigl.html#a720d55d920ca7659102fd8dd267e7936',1,'igl::harmonic(const Eigen::SparseCompressedBase&lt; DerivedL &gt; &amp;L, const Eigen::SparseCompressedBase&lt; DerivedM &gt; &amp;M, const Eigen::MatrixBase&lt; Derivedb &gt; &amp;b, const Eigen::MatrixBase&lt; Derivedbc &gt; &amp;bc, const int k, Eigen::PlainObjectBase&lt; DerivedW &gt; &amp;W)'],['../namespaceigl.html#aba39f8e29962d636cfae080188ec1da7',1,'igl::harmonic(const Eigen::SparseCompressedBase&lt; DerivedL &gt; &amp;L, const Eigen::SparseCompressedBase&lt; DerivedM &gt; &amp;M, const int k, DerivedQ &amp;Q)'],['../namespaceigl.html#accdfdc1795f3cd0fbf66aeb3ca316604',1,'igl::harmonic(const Eigen::MatrixBase&lt; DerivedV &gt; &amp;V, const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, const int k, DerivedQ &amp;Q)']]],
  ['harwell_5fboeing_2',['harwell_boeing',['../namespaceigl.html#a073322f93d4fd2e161868d738abdfc09',1,'igl']]],
  ['hausdorff_3',['hausdorff',['../namespaceigl.html#a64901d7f496bd1cccbccceddbc091603',1,'igl::hausdorff(const Eigen::MatrixBase&lt; DerivedVA &gt; &amp;VA, const Eigen::MatrixBase&lt; DerivedFA &gt; &amp;FA, const Eigen::MatrixBase&lt; DerivedVB &gt; &amp;VB, const Eigen::MatrixBase&lt; DerivedFB &gt; &amp;FB, Scalar &amp;d)'],['../namespaceigl.html#a3de06347c75f90acb8cc0114c7249e58',1,'igl::hausdorff(const Eigen::MatrixBase&lt; DerivedV &gt; &amp;V, const std::function&lt; Scalar(const Scalar &amp;, const Scalar &amp;, const Scalar &amp;)&gt; &amp;dist_to_B, Scalar &amp;l, Scalar &amp;u)']]],
  ['heat_5fgeodesics_5fprecompute_4',['heat_geodesics_precompute',['../namespaceigl.html#a12efa6b8fc863b52dd131d478a456802',1,'igl::heat_geodesics_precompute(const Eigen::MatrixBase&lt; DerivedV &gt; &amp;V, const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, const Scalar t, HeatGeodesicsData&lt; Scalar &gt; &amp;data)'],['../namespaceigl.html#affbddd3e363a529044cd4bd848b278f4',1,'igl::heat_geodesics_precompute(const Eigen::MatrixBase&lt; DerivedV &gt; &amp;V, const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, HeatGeodesicsData&lt; Scalar &gt; &amp;data)']]],
  ['heat_5fgeodesics_5fsolve_5',['heat_geodesics_solve',['../namespaceigl.html#ae558cd690e05ad2e41caa655251e23c4',1,'igl']]],
  ['hessian_6',['hessian',['../namespaceigl.html#a8e6dbdaae94657379ac8491942082d20',1,'igl']]],
  ['hessian_5fenergy_7',['hessian_energy',['../namespaceigl.html#a5d3d292215a6020d9e70cd7cfdd29ec1',1,'igl']]],
  ['histc_8',['histc',['../namespaceigl.html#a7e66c7ad3404c4e5a43a2ecaf1c21819',1,'igl::histc(const Eigen::MatrixBase&lt; DerivedX &gt; &amp;X, const Eigen::MatrixBase&lt; DerivedE &gt; &amp;E, Eigen::PlainObjectBase&lt; DerivedN &gt; &amp;N, Eigen::PlainObjectBase&lt; DerivedB &gt; &amp;B)'],['../namespaceigl.html#af74c4ce0e45c4fc1ab9e958c93ef4437',1,'igl::histc(const Eigen::MatrixBase&lt; DerivedX &gt; &amp;X, const Eigen::MatrixBase&lt; DerivedE &gt; &amp;E, Eigen::PlainObjectBase&lt; DerivedB &gt; &amp;B)'],['../namespaceigl.html#a946a214630848d43ddc7df74e00f4d57',1,'igl::histc(const typename DerivedE::Scalar &amp;x, const Eigen::MatrixBase&lt; DerivedE &gt; &amp;E, typename DerivedE::Index &amp;b)']]],
  ['hsv_5fto_5frgb_9',['hsv_to_rgb',['../namespaceigl.html#a840674ca4222700909ca8197e27800a5',1,'igl::hsv_to_rgb(const T *hsv, T *rgb)'],['../namespaceigl.html#a67a8efe9fd3b48830cd07fd2fb45ece6',1,'igl::hsv_to_rgb(const T &amp;h, const T &amp;s, const T &amp;v, T &amp;r, T &amp;g, T &amp;b)'],['../namespaceigl.html#a3e2573040155e553e83f6b2098417ed2',1,'igl::hsv_to_rgb(const Eigen::PlainObjectBase&lt; DerivedH &gt; &amp;H, Eigen::PlainObjectBase&lt; DerivedR &gt; &amp;R)']]]
];
