var searchData=
[
  ['tan_5fhalf_5fangle_0',['tan_half_angle',['../namespaceigl.html#aca626f9c0a1f205b884fc1c6787c6a59',1,'igl']]],
  ['tet_5ftet_5fadjacency_1',['tet_tet_adjacency',['../namespaceigl.html#ab9fcd72a6173a2c6d4e4651a706b2911',1,'igl::tet_tet_adjacency(const Eigen::MatrixBase&lt; DerivedT &gt; &amp;T, Eigen::PlainObjectBase&lt; DerivedTT &gt; &amp;TT, Eigen::PlainObjectBase&lt; DerivedTTi &gt; &amp;TTi)'],['../namespaceigl.html#ada72de8eeac466f8cb2a52016a1bd1cf',1,'igl::tet_tet_adjacency(const Eigen::MatrixBase&lt; DerivedT &gt; &amp;T, Eigen::PlainObjectBase&lt; DerivedTT &gt; &amp;TT)']]],
  ['tetrahedralized_5fgrid_2',['tetrahedralized_grid',['../namespaceigl.html#a09d82782b314ba8729b05712387f7ec4',1,'igl::tetrahedralized_grid(const int nx, const int ny, const int nz, const TetrahedralizedGripType type, Eigen::PlainObjectBase&lt; DerivedGV &gt; &amp;GV, Eigen::PlainObjectBase&lt; DerivedGT &gt; &amp;GT)'],['../namespaceigl.html#adb7ca2123abe298822cf2bf15b1421b6',1,'igl::tetrahedralized_grid(const Eigen::MatrixBase&lt; DerivedGV &gt; &amp;GV, const Eigen::MatrixBase&lt; Derivedside &gt; &amp;side, const TetrahedralizedGripType type, Eigen::PlainObjectBase&lt; DerivedGT &gt; &amp;GT)']]],
  ['timer_3',['Timer',['../classigl_1_1Timer.html#a4492debe2d7447a5915c9fd9911cebc8',1,'igl::Timer']]],
  ['topological_5fhole_5ffill_4',['topological_hole_fill',['../namespaceigl.html#abab7f0da5952b09f2ba7ffee0f9a0d58',1,'igl']]],
  ['trackball_5',['trackball',['../namespaceigl.html#a46c31d9f94cfdba0d5da1b69f4f4d968',1,'igl::trackball(const double w, const double h, const Q_type speed_factor, const Q_type *down_quat, const double down_mouse_x, const double down_mouse_y, const double mouse_x, const double mouse_y, Q_type *quat)'],['../namespaceigl.html#aaf9d8f7f6bbca5f24365f3ce5f401f9a',1,'igl::trackball(const double w, const double h, const double speed_factor, const Eigen::Quaternion&lt; Scalardown_quat &gt; &amp;down_quat, const double down_mouse_x, const double down_mouse_y, const double mouse_x, const double mouse_y, Eigen::Quaternion&lt; Scalarquat &gt; &amp;quat)'],['../namespaceigl.html#a4c72a7f89ae16b8e5196c4cd37fb2689',1,'igl::trackball(const double w, const double h, const Q_type speed_factor, const double down_mouse_x, const double down_mouse_y, const double mouse_x, const double mouse_y, Q_type *quat)']]],
  ['transpose_5fblocks_6',['transpose_blocks',['../namespaceigl.html#a5fa327db1af41a1e29e474981b963409',1,'igl']]],
  ['triangle_5ffan_7',['triangle_fan',['../namespaceigl.html#a9ce1a2b984f20466ffc7732ab29501ba',1,'igl::triangle_fan(const Eigen::MatrixBase&lt; DerivedE &gt; &amp;E, Eigen::PlainObjectBase&lt; Derivedcap &gt; &amp;cap)'],['../namespaceigl.html#a6b17a92c69587c651fe1b4d549235a9d',1,'igl::triangle_fan(const Eigen::MatrixXi &amp;E)']]],
  ['triangle_5ftriangle_5fadjacency_8',['triangle_triangle_adjacency',['../namespaceigl.html#ae07b1e4d35569138ffa0d8a874f0e24f',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, Eigen::PlainObjectBase&lt; DerivedTT &gt; &amp;TT, Eigen::PlainObjectBase&lt; DerivedTTi &gt; &amp;TTi)'],['../namespaceigl.html#afc80c379b811624a97c1ed29ba4df0fb',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedEMAP &gt; &amp;EMAP, const Eigen::MatrixBase&lt; DeriveduEC &gt; &amp;uEC, const Eigen::MatrixBase&lt; DeriveduEE &gt; &amp;uEE, const bool construct_TTi, std::vector&lt; std::vector&lt; std::vector&lt; TTIndex &gt; &gt; &gt; &amp;TT, std::vector&lt; std::vector&lt; std::vector&lt; TTiIndex &gt; &gt; &gt; &amp;TTi)'],['../namespaceigl.html#ab979438c0daba73490363a56fc67f54a',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedE &gt; &amp;E, const Eigen::MatrixBase&lt; DerivedEMAP &gt; &amp;EMAP, const std::vector&lt; std::vector&lt; uE2EType &gt; &gt; &amp;uE2E, const bool construct_TTi, std::vector&lt; std::vector&lt; std::vector&lt; TTIndex &gt; &gt; &gt; &amp;TT, std::vector&lt; std::vector&lt; std::vector&lt; TTiIndex &gt; &gt; &gt; &amp;TTi)'],['../namespaceigl.html#ad091a40b270aa5030a3dd0909e6402e6',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, const bool construct_TTi, std::vector&lt; std::vector&lt; std::vector&lt; TTIndex &gt; &gt; &gt; &amp;TT, std::vector&lt; std::vector&lt; std::vector&lt; TTiIndex &gt; &gt; &gt; &amp;TTi)'],['../namespaceigl.html#a5ea1a1ba3c8bee980c00db518fb9f443',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, std::vector&lt; std::vector&lt; std::vector&lt; TTIndex &gt; &gt; &gt; &amp;TT)'],['../namespaceigl.html#a99e6fd086c1507cb6b02df0b458566cd',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, std::vector&lt; std::vector&lt; std::vector&lt; TTIndex &gt; &gt; &gt; &amp;TT, std::vector&lt; std::vector&lt; std::vector&lt; TTiIndex &gt; &gt; &gt; &amp;TTi)'],['../namespaceigl.html#a7210f2492117b1c482907e6a47dbed75',1,'igl::triangle_triangle_adjacency(const Eigen::MatrixBase&lt; DerivedF &gt; &amp;F, Eigen::PlainObjectBase&lt; DerivedTT &gt; &amp;TT)']]],
  ['triangle_5ftriangle_5fadjacency_5fextracttt_9',['triangle_triangle_adjacency_extractTT',['../namespaceigl.html#a45cd01351200f4312c4fa5abef9c63a1',1,'igl']]],
  ['triangle_5ftriangle_5fadjacency_5fextracttti_10',['triangle_triangle_adjacency_extractTTi',['../namespaceigl.html#a81887c23c0079fb92f46a517cd42f752',1,'igl']]],
  ['triangle_5ftriangle_5fadjacency_5fpreprocess_11',['triangle_triangle_adjacency_preprocess',['../namespaceigl.html#add74393b2dabd37b8efd0a7c2145372a',1,'igl']]],
  ['triangles_5ffrom_5fstrip_12',['triangles_from_strip',['../namespaceigl.html#ae67465786e131443ebdb6bdae0aa701f',1,'igl']]],
  ['triangulated_5fgrid_13',['triangulated_grid',['../namespaceigl.html#a3be3b842294c1e29d654ace1e4f735ca',1,'igl::triangulated_grid(const XType &amp;nx, const YType &amp;ny, Eigen::PlainObjectBase&lt; DerivedGV &gt; &amp;GV, Eigen::PlainObjectBase&lt; DerivedGF &gt; &amp;GF)'],['../namespaceigl.html#a82c16be739961936bc5159688a4c7683',1,'igl::triangulated_grid(const XType &amp;nx, const YType &amp;ny, Eigen::PlainObjectBase&lt; DerivedGF &gt; &amp;GF)']]],
  ['two_5faxis_5fvaluator_5ffixed_5fup_14',['two_axis_valuator_fixed_up',['../namespaceigl.html#aaef42c6f3251414c7485b4d1433a54e4',1,'igl']]]
];
